dist: trusty
sudo: required

branches:
  only:
    - gh-pages
    - /.*/

# Environment variables
env:
  global:
    - GH_REPO_NAME: DrShadowStack
    - GH_REPO_REF: github.com/zwimer/DrShadowStack.git

# Install dependencies
install:
  - set -e
  - ./travis-scripts/install.sh

# Build and test
script:
  - set -e
  - cd $TRAVIS_BUILD_DIR
  - ./travis-scripts/setup.sh
  - ./travis-scripts/build.sh
  - ./travis-scripts/gen_docs.sh
  - ./travis-scripts/update_current_commit.sh # Must be run last
