sudo: false

# Blacklist
branches:
  except:
      - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: DrShadowStack
    - DOXYFILE: $TRAVIS_BUILD_DIR
    - GH_REPO_REF: github.com/zwimer/DrShadowStack.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
# script:
#   - make

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x gen_docs.sh
  - ./gen_docs.sh
