dist: trusty
sudo: required

# Blacklist
branches:
  except:
      - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: DrShadowStack
    - DOXYFILE: $TRAVIS_BUILD_DIR
    - GH_REPO_REF: github.com/zwimer/DrShadowStack.git

# Install dependencies
install:
  - sudo apt-get update
  - sudo apt-get install --yes doxygen graphviz

# Build your code e.g. by calling make
script:
  - set -e
  - cd $TRAVIS_BUILD_DIR
  - chmod +x gen_docs.sh
  - ./gen_docs.sh

# Generate and deploy documentation
# after_success:
