dist: trusty
sudo: required

branches:
  only:
    - gh-pages
    - /.*/

# Environment variables
env:
  global:
    - GH_REPO_NAME: DrShadowStack
    - GH_REPO_REF: github.com/zwimer/DrShadowStack.git

# Install dependencies
install:
  - sudo apt-get update
  - sudo apt-get install --yes doxygen graphviz
  - sudo apt-get install --yes libboost-program-options-dev libboost-filesystem-dev
  - sudo apt-get install --yes cmake

# Build and test
script:
  - set -e
  - cd $TRAVIS_BUILD_DIR
  - ./travis_scripts/setup.sh
  - ./travis_scripts/build.sh
  - ./travis_scripts/gen_docs.sh
