#!/bin/bash
set -e
cd $TRAVIS_BUILD_DIR

# Do nothing if this commit should be skipped
if [ -f ./travis_scripts/is_autogenerated_and_should_skip ]; then
	echo "Removing the 'skip-commit' file..."
	rm -f ./travis_scripts/is_autogenerated_and_should_skip
	exit 0
fi


# Make a working directory for this script
mkdir update_current_commit
cd update_current_commit

# Get current branch
echo 'Getting branch...'
if [ -z "$TRAVIS_PULL_REQUEST_BRANCH" ]; then 
	BRANCH="$TRAVIS_BRANCH"
else
	BRANCH="$TRAVIS_PULL_REQUEST_BRANCH"
fi
echo "$BRANCH"

# Clone the repo
echo 'Cloning current branch...'
git clone -b "$BRANCH" https://git@$GH_REPO_REF
cd $GH_REPO_NAME

# Format the code
echo 'Formatting code...'
clang-format-7 -i -style=file ./src/*pp
git add ./src/

# Update the change log
echo 'Updating changelog...'
github_changelog_generator -u zwimer -p DrShadowStack
git add ./CHANGELOG.md

# Note that the next commit should skip build
touch ./travis_scripts/is_autogenerated_and_should_skip
git add ./travis_scripts/is_autogenerated_and_should_skip

# Update the repo
echo 'Updating repo...'
git commit -m "Travis-CI: Formatted code and updated changelog" | true
git remote rm origin
git remote add origin https://zwimer:$GH_REPO_TOKEN@github.com/zwimer/$GH_REPO_NAME
git push -u origin "$BRANCH" | true
