#!/bin/sh
set -e
cd $TRAVIS_BUILD_DIR

# Do nothing if this commit should be skipped
if [ -f ./travis-scripts/is_autogenerated_and_should_skip ]; then
	exit 0
fi


# Setup git
echo 'Setting up git...'
git config --global push.default simple
git config user.name "Travis CI"
git config user.email "travis@travis-ci.org"
